export const INIT_CROSSWORD = 'INIT_CROSSWORD';
export const INIT_CROSSWORD_SUCCESS = 'INIT_CROSSWORD_SUCCESS';
export const INIT_CROSSWORD_FAIL = 'INIT_CROSSWORD_FAIL';
export const UPDATE_CROSSWORD = 'UPDATE_CROSSWORD';
export const UPDATE_CLUE_DIRECTION = 'UPDATE_CLUE_DIRECTION';
export const GET_SQUARE_VALUES = 'GET_SQUARE_VALUES';
export const CLEAR_USER_VALUES = 'CLEAR_USER_VALUES';