export const INIT_CROSSWORD = 'INIT_CROSSWORD';
export const INIT_CROSSWORD_SUCCESS = 'INIT_CROSSWORD_SUCCESS';
export const INIT_CROSSWORD_FAIL = 'INIT_CROSSWORD_FAIL';
export const UPDATE_CROSSWORD = 'UPDATE_CROSSWORD';